### ISSUE TITLE
Export to xlsx

### ISSUE THREAD

**Issue by Chingling152** [Chingling152/my-financial-hub#16]
## Introduction
Exports a filter or all information to a xlsx file.
Create sheets for 
* Earns
* Expenses
* Accounts
Or only the full history

## Milestone
- [ ] Architecture
  - [ ] TODO : Add tasks for Architecture
- [ ] Endpoints
  - [ ] TODO : Add tasks for Endpoint
- [ ] Tests
  - [ ] TODO : Add tasks for Test
