### ISSUE TITLE
Architecture tests

### ISSUE THREAD

**Issue by Chingling152** [Chingling152/my-financial-hub#28]
## Introduction
Tests to ensure that the project has organized layers.

## Milestone
- [ ] Tests
  - [ ] Create Architecture tests for Models
  - [ ] Create Architecture tests for Entities
  - [ ] Create Architecture tests for Controller Layer
  - [ ] Create Architecture tests for Service Layer
  - [ ] Create Architecture tests for Repository Layer
