### ISSUE TITLE
Earnings and Expenses

### ISSUE THREAD

**Issue by Chingling152** [Chingling152/my-financial-hub#3]
## Introduction
Transactions created by the user to add or remove money from one account.
Both Earnings and Expenses should have : 
- Amount (always a positive number, even when is Expenses)
- Date of the transaction
- Description (optional)
- Category of the transactions (requires #2 ) 
- Status (paid/not paid or spent/not spent)
- Account where the transaction was made (requires #1 ) 

## Tasks
- [x] Architecture
  - [x] SQL Table DDL 
  - [x] Project Structure
  - [x] Class Architecture
- [x] Endpoints
  - [x] Earnings / Expenses
    - [x] Create 
    - [x] Update 
    - [x] Delete
    - [x] Get
      - [x] Filter by date (Month)
      - [x] Filter between dates
      - [x] Filter by accounts
      - [x] Filter by categories (requires #2 )
      - [x] Filter by type
      - [x] Filter by status
- [x] Tests
  - [x] Create Earning / Expense
  - [x] Update Earning / Expense
  - [x] Delete Earning / Expense
  - [x] Get Earning / Expense
