### ISSUE TITLE
Improve performance

### ISSUE THREAD

**Issue by Chingling152** [Chingling152/my-financial-hub#32]
## Milestone
- [ ] Tests
  - [ ] Queries performance
    - [ ] Currently query system
    - [ ] IQueryable w/multiple wheres
    - [ ] Expressions
  - [ ] Async Performance
    - [ ] Entity Framework Async Method 
  - [ ] Stress tests
