### ISSUE TITLE
Integration tests

### ISSUE THREAD

**Issue by Chingling152** [Chingling152/my-financial-hub#45]
## Introduction
Create a project of integration tests to the main api

## Milestone
- [x] Tests
  - [x] Accounts endpoint test
  - [x] Transactions endpoint test
  - [x] Category endpoint test
